[project]
name = "gittool"
version = "0.1.1"
description = "Default template for PDM package"
authors = [
    {name = "Jimmy Lin", email = "b00502013@gmail.com"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
